export const SUCCESS_AUTH = 'SUCCESS_AUTH';
export const START_AUTH = 'START_AUTH';

export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

export const START_REGISTRATION = 'START_REGISTRATION';
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';

export const START_LOADING = 'START_LOADING';
export const SUCCESS_LOADING = 'SUCCESS_LOADING';
export const ERROR_LOADING = 'ERROR_LOADING';
