name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setups-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      - name: npm deploy
      run: |
        npm run deploy